import io
import zipfile
import json
import logging
from typing import Dict, Any, Optional
from backend.app.core.pdf_generator import pdf_report_generator

logger = logging.getLogger(__name__)


class CodeExporter:
    """
    Exports structured BDD test suites to runnable Pytest Python scripts,
    Gherkin .feature files, and complete downloadable ZIP bundles.
    """

    @staticmethod
    def _to_dict(suite: Any) -> Dict[str, Any]:
        if hasattr(suite, "model_dump"):
            return suite.model_dump()
        if isinstance(suite, dict):
            return suite
        return {}

    @staticmethod
    def to_pytest_script(test_suite: Dict[str, Any], target_url: str = "https://example.com") -> str:
        suite_dict = CodeExporter._to_dict(test_suite)
        suite_id = suite_dict.get("id", "suite_001")
        url = suite_dict.get("target_url") or target_url
        scenarios = suite_dict.get("scenarios", [])

        header = (
            '"""\n'
            'AutoHealQA Generated Pytest-Playwright Test Suite\n'
            f'Suite ID: {suite_id}\n'
            f'Target URL: {url}\n'
            'Generated by AutoHeal Engine\n'
            '"""\n\n'
            'import pytest\n'
            'from playwright.async_api import Page, expect\n\n'
        )

        script = header

        for scenario in scenarios:
            sc_id = scenario.get("id", "sc").lower().replace("-", "_")
            sc_title = scenario.get("title", "scenario").lower().replace(" ", "_")
            script += f"@pytest.mark.asyncio\nasync def test_{sc_id}_{sc_title}(page: Page):\n"
            script += f'    """Scenario: {scenario.get("title")}"""\n'
            script += f'    await page.goto("{url}")\n'

            for step in scenario.get("test_steps", []):
                action = step.get("action", "").lower()
                target = step.get("target_description", "")
                selector = step.get("selector_hint") or "text=" + target

                if action in ["click", "press"]:
                    script += f'    await page.click("{selector}")\n'
                elif action in ["fill", "type", "enter"]:
                    val = step.get("input_value") or step.get("value") or "sample text"
                    script += f'    await page.fill("{selector}", "{val}")\n'
                elif action in ["verify", "check", "assert"]:
                    script += f'    await expect(page.locator("{selector}")).to_be_visible()\n'
                elif action in ["navigate", "open"]:
                    script += f'    await page.goto("{url}")\n'
                else:
                    script += f'    # Step: {action} on {target}\n'

            script += "\n\n"

        return script.strip() + "\n"

    @staticmethod
    def to_gherkin_feature(test_suite: Dict[str, Any]) -> str:
        suite_dict = CodeExporter._to_dict(test_suite)
        suite_id = suite_dict.get("id", "suite_001")
        title = suite_dict.get("title") or f"AutoHealQA Test Suite ({suite_id})"
        scenarios = suite_dict.get("scenarios", [])

        feature = f"Feature: {title}\n\n"
        for scenario in scenarios:
            feature += f"  Scenario: {scenario.get('title', 'BDD Scenario')}\n"
            gherkin_body = scenario.get('gherkin_text', '')
            indented = "\n".join(["    " + line for line in gherkin_body.splitlines()])
            feature += f"{indented}\n\n"

        return feature.strip() + "\n"

    @staticmethod
    def create_full_suite_zip(test_suite: Dict[str, Any], latest_run: Optional[Dict[str, Any]] = None) -> bytes:
        """
        Creates an in-memory zip bundle containing .py, .feature, report.html, and metadata.json.
        """
        buffer = io.BytesIO()
        suite_dict = CodeExporter._to_dict(test_suite)
        suite_id = suite_dict.get("id", "suite_001")

        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # 1. Pytest Python Script
            py_code = CodeExporter.to_pytest_script(suite_dict)
            zf.writestr(f"tests/test_{suite_id}.py", py_code)

            # 2. Gherkin Feature File
            feature_code = CodeExporter.to_gherkin_feature(suite_dict)
            zf.writestr(f"features/{suite_id}.feature", feature_code)

            # 3. Metadata JSON
            zf.writestr("suite_metadata.json", json.dumps(suite_dict, indent=2))

            # 4. Report HTML if run exists
            if latest_run:
                report_html = pdf_report_generator.generate_html_report(latest_run)
                zf.writestr("executive_report.html", report_html)

            # 5. README.md guide
            readme = f"""# AutoHealQA Exported Test Package ({suite_id})

## Quick Start:
1. Install dependencies:
   ```bash
   pip install pytest pytest-playwright
   playwright install
   ```
2. Run pytest suite:
   ```bash
   pytest tests/test_{suite_id}.py -v
   ```
3. Open `executive_report.html` in any browser to inspect executive summary metrics.
"""
            zf.writestr("README.md", readme)

        buffer.seek(0)
        return buffer.getvalue()

    @staticmethod
    def export_to_python_pytest(test_suite: Any) -> str:
        suite_dict = CodeExporter._to_dict(test_suite)
        target_url = suite_dict.get("target_url") or "https://example.com"
        return CodeExporter.to_pytest_script(suite_dict, target_url)

    @staticmethod
    def export_to_gherkin_feature(test_suite: Any) -> str:
        suite_dict = CodeExporter._to_dict(test_suite)
        return CodeExporter.to_gherkin_feature(suite_dict)


code_exporter = CodeExporter()
